/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./src/components/dialogs/baseDialog.vue')['default']
    DiaitalApps: typeof import('./src/components/home/diaitalApps.vue')['default']
    DiaitalDate: typeof import('./src/components/home/diaitalDate.vue')['default']
    DiaitalHeader: typeof import('./src/components/home/diaitalHeader.vue')['default']
    DiaitalSetting: typeof import('./src/components/home/diaitalSetting.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOverlay: typeof import('element-plus/es')['ElOverlay']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDialog: typeof import('./src/components/dialogs/themeDialog.vue')['default']
    ThemeSetting: typeof import('./src/components/settings/themeSetting.vue')['default']
    Wallpaper: typeof import('./src/components/settings/wallpaper.vue')['default']
    WallpaperSetting: typeof import('./src/components/settings/wallpaperSetting.vue')['default']
  }
}
